### PR TITLE
Prepare pypi release

### PR DESCRIPTION
**Pull request by sallner**
I prepared  the necessary changes for a PyPI release and would be happy about a comment and/or a decision on how to proceed from now. 

Are you willing to release it? 
Should my company (gocept) take over the release process on PyPI? In that case, we have to decide whether the metadata is adequate.

### CODE REVIEW

**Comment by sallner** [comment]
@christian-schlichtherle  Could you help me with that?

**Comment by christian-schlichtherle** [comment]
Hi. I'm sorry for the late response, but I got the notification just now.

**Comment by sallner** [comment]
Thank you for merging the PR. Concenring #1 , do you plan to release the package on PyPI?

**Comment by christian-schlichtherle** [comment]
Please go ahead and release under your own name.

**Pull request merged**
